leftnav:
- identifier: 3e95fb4b-e99f-64dd-50b2-c02b053d38ea
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 3e5908a6-91ac-b5f9-439c-c37900c37063
  name: Instructor Insights
  pageRef: /pages/instructor-insights/
  weight: 20
- identifier: 65e9712b-83ef-458d-b862-833edbcf5627
  name: 'Week 0: About this Course'
  pageRef: /pages/week-0-about-this-course-good
  weight: 30
- identifier: 1fc7b382-9d76-494a-9016-3f4323c07fe7
  name: 'Week 1: Flatbed Scanner'
  pageRef: /video_galleries/week-1-flatbed-scanner
  weight: 40
- identifier: 6685ca14-96f2-4543-9c9c-8e6deeec2962
  name: 'Week 2: Camera Basics'
  pageRef: /video_galleries/week-2-camera-basics
  weight: 50
- identifier: 3a8df3ce-3627-4816-9348-b8119201f470
  name: 'Week 3: Light'
  pageRef: /video_galleries/week-3-light
  weight: 60
- identifier: 983a6d1e-410d-436a-97eb-5fc2c86e5fc4
  name: 'Week 4: Mobile Devices and Video'
  pageRef: /video_galleries/week-4-mobile-devices-and-video
  weight: 70
- identifier: e109eac6-423e-4adc-9802-4c24ee34d6c5
  name: 'Week 5: Presenting Your Work'
  pageRef: /video_galleries/week-5-presenting-your-work
  weight: 80
- identifier: 6d81eed3-1284-4fb9-b8ad-aaade23b6c24
  name: 'Week 6: Case Studies'
  pageRef: /video_galleries/week-6-case-studies
  weight: 90
- identifier: f4d9bb87-5c3a-4ee5-9752-d3193dfe4838
  name: How-To-Do-It Tutorials
  pageRef: /video_galleries/how-to-do-it-tutorials2
  weight: 100
- identifier: 32cb2374-4b34-4e87-8370-1c085d6e7a62
  name: Guest Interviews
  pageRef: /video_galleries/guest-interviews
  weight: 110
- identifier: 76026f86-1978-0149-19bb-108b31efc99c
  name: Additional Materials
  pageRef: /pages/additional-materials
  weight: 120
- identifier: b6ad918e-913d-2617-f4fa-97e028cd36ad
  name: Coming Full Circle Back to Science
  pageRef: /pages/instructor-insights/instructor-background-coming-full-circle-back-to-science
  parent: 3e5908a6-91ac-b5f9-439c-c37900c37063
  weight: 10
- identifier: 97e48da7-126b-04f0-2faa-6006c668de19
  name: 'Nothing Better than a Picture '
  pageRef: /pages/instructor-insights/nothing-better-than-a-picture
  parent: 3e5908a6-91ac-b5f9-439c-c37900c37063
  weight: 20
- identifier: 5ee9f6d2-da58-4ce8-e720-1f6e29bd5f9f
  name: Providing Meaningful Feedback in a MOOC
  pageRef: /pages/instructor-insights/providing-meaningful-feedback-in-a-mooc-environment
  parent: 3e5908a6-91ac-b5f9-439c-c37900c37063
  weight: 30
- identifier: 80f03020-3474-5911-66b0-b9c00eddd75a
  name: Collaborating as a Teaching Team
  pageRef: /pages/instructor-insights/collaborating-as-a-teaching-team
  parent: 3e5908a6-91ac-b5f9-439c-c37900c37063
  weight: 40
